


// —————————————— 
// <auto-generated> 
//	This code was auto-generated 01/22/2021 05:38:32 
//	T4 template generates viewmodel's code 
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–
using System;
using System.Collections.Generic;
namespace AgroExpCore.Domain
{

    /// <summary>
    ///
    /// A Company view model
    ///   
    ///       MANUAL UPDATES REQUIRED! 
    ///       NOTE use PM console to update database with new entity : 
    ///            PM>add-migration AddCompany
    ///            PM>update-database
    ///
    /// </summary>
    public class CompanyViewModel : BaseDomain
    {
	  		public string Name { get; set; } 
			public string TaxCode { get; set; } 
			public string UserName { get; set; } 
			public string Email { get; set; } 
			public string Description { get; set; } 
			public bool IsActive { get; set; } 
	} 
	     
}