

// —————————————— 
// <auto-generated> 
//	This code was auto-generated 01/22/2021 05:38:36 
//	T4 template generates viewmodel mapping profile code 
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–
using System;
using System.Collections.Generic;
using System.Text;
using AutoMapper;
using AgroExpCore.Entity;
namespace AgroExpCore.Domain.Mapping
{
    /// <summary>
    /// 
    /// </summary>
    public partial class MappingProfile : Profile
    {
        partial void SetAddedMappingProfile()
        {
    			CreateMap<CompanyViewModel, Company>();
			CreateMap<Company, CompanyViewModel>();
	 
		}	
	} 
}

